### ISSUE TITLE
Bug no programa lembrete seleciona vários lembretes

### ISSUE THREAD

**Issue by Geofisicando** [Dirack/Shell-Script#7]
O programa lembrete, se as chaves são parecidas, retorna vários valores de lembrete sem separar o lembrete selecionado dos lembretes parecidos. Exemplo, cadastrei lembretes _cabecalho_ e _templateCabecalho_, ao chamar o primeiro lembrete, o resultado é este:

```shell
~$  lembrete -l cabecalho
LEMBRETE= cabecalho
templateCabecalho
DATA= 03/07/2019
03/07/2019
HORA= 09:28:45
09:31:02
MENSAGEM= Programa deve ter templates dos cabeçalhos
cabecalho deve reconhecer arquivo pela extensão
```

**Comment by Dirack** [comment]
Bug corrigido
