### ISSUE TITLE
O programa cabecalho poderia ter um arquivo template e variáveis de sistema

### ISSUE THREAD

**Issue by Geofisicando** [Dirack/Shell-Script#8]
@Dirack, o programa _cabecalho_ exige que o programador digite constantemente as suas informações pessoais para cadaarquivo que produzir. O que poderia ser substituído por um arquivo de configuração que carrega variáveis de sistema como .nome .email etc

**Comment by Dirack** [comment]
Feature adicionada ao programa cabecalho
