### ISSUE TITLE
cabecalho poderia reconhecer arquivo pela extensão

### ISSUE THREAD

**Issue by Geofisicando** [Dirack/Shell-Script#9]
O programa _cabecalho_ poderia reconhecer o arquivo a ser gerado pela extensão. Isto seria mais prático que usar flags para escolher a linguagem do arquivo. Estas flags poderiam ser utilizadas somente quando fosse necessário forçar a identificação da linguagem

**Comment by Dirack** [comment]
Esta feature será provavelmente incorporada nas próximas versões da biblioteca. Por enquanto, o programa _cabecalho_ seguirá o seu padrão de uso atual.
